ftype txtfile=c:\emacs\bin\emacsclientw -na c:\emacs\bin\runemacs "%1"
ftype EmacsLisp=c:\emacs\bin\emacsclientw -na c:\emacs\bin\runemacs "%1"
ftype CodeFile=c:\emacs\bin\emacsclientw -na c:\emacs\bin\runemacs "%1"
assoc .txt=txtfile
assoc .text=txtfile
assoc .log=txtfile
assoc .config=txtfile
assoc .el=EmacsLisp
rem assoc .c=CodeFile
rem assoc .h=CodeFile
